/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || 'no-api-key-set',
config.sitecoreApiHost = process.env.SITECORE_API_HOST || '',
config.jssAppName = process.env.JSS_APP_NAME || 'Rotork',
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge',
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en',
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || '/sitecore/api/graph/edge',
config.sites = process.env.SITES || '[]',
module.exports = config;